project:
  type: website
  output-dir: docs

website:
  navbar:
    collapse: true
    collapse-below: sm
    logo: images/02.svg
    href: http://stat.hanyang.ac.kr
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - text: "Lab"
        menu:
          - text: "Lab 00: Install R and R Studio"
          - text: "Lab 01 ~ Lab 12"
    right: 
      - icon: house-door-fill
        href: https://seoncheolpark.github.io
  page-footer: "Copyright 2025, Seoncheol Park"       
format:
  html:
    theme:
      light: [minty, theme.scss]
      dark: [minty, theme-dark.scss]
    fontsize: 1.1em
    linestretch: 1.7
    css: styles.css
    toc: true
  
editor: visual

